# Generated by Django 3.2.12 on 2024-01-04 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=255, unique=True, verbose_name='email address')),
                ('contact_number', models.CharField(max_length=100)),
                ('inquiry_message', models.TextField(default='')),
                ('assigned_user', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service', models.CharField(max_length=100)),
                ('bio', models.TextField(default='')),
                ('experience', models.IntegerField(default='1')),
                ('rating', models.FloatField(default='3')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('business_description', models.TextField()),
                ('business_category', models.CharField(max_length=255)),
                ('pan_number', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('staff_name', models.CharField(max_length=40)),
                ('isFinished', models.CharField(default='No', max_length=15)),
                ('message', models.TextField()),
                ('replied', models.BooleanField(default=False)),
                ('reply_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber')], default='Electrician', max_length=50)),
                ('day', models.CharField(choices=[('2023-11-03', '2023-11-03'), ('2023-11-04', '2023-11-04'), ('2023-11-05', '2023-11-05'), ('2023-11-06', '2023-11-06'), ('2023-11-07', '2023-11-07'), ('2023-11-08', '2023-11-08'), ('2023-11-09', '2023-11-09')], default='Monday', max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('isFinished', models.CharField(default='No', max_length=15)),
                ('time', models.CharField(blank=True, choices=[('9 am', ' 10 am '), ('10 am', ' 11 am ')], default='3 PM', max_length=10, null=True)),
                ('staff', models.CharField(default='Not assigned', max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
