# Generated by Django 3.2.12 on 2024-01-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
    ]
