# Generated by Django 3.2.12 on 2024-01-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20240104_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
