# Generated by Django 3.2.12 on 2024-01-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(default='Cash On Delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
