# Generated by Django 3.2.12 on 2024-01-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20240105_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.CharField(default='Not assigned', max_length=50),
        ),
    ]
