# Generated by Django 3.2.12 on 2024-01-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_appointment_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
