# Generated by Django 3.0.5 on 2024-01-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20240107_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('feedback', 'Feedback')], default='complaint', max_length=20),
        ),
    ]
