# Generated by Django 3.0.5 on 2024-01-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20240109_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
