# Generated by Django 3.0.5 on 2024-01-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20240109_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
