# Generated by Django 3.0.5 on 2024-01-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20240110_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='inquiry_message',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='rating',
        ),
        migrations.AddField(
            model_name='appointment',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='cumulative_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
