# Generated by Django 3.0.5 on 2024-01-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20240112_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
