# Generated by Django 3.0.5 on 2024-01-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_appointment_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='photo',
            field=models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images'),
        ),
    ]
