# Generated by Django 3.0.5 on 2024-01-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20240112_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
