# Generated by Django 3.0.5 on 2024-01-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20240115_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='contact_number',
            new_name='number',
        ),
    ]
