# Generated by Django 3.0.5 on 2024-01-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20240115_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
