# Generated by Django 3.0.5 on 2024-01-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20240115_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
