# Generated by Django 3.0.5 on 2024-01-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_auto_20240116_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images'),
        ),
    ]
