# Generated by Django 3.0.5 on 2024-01-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='CA_image',
            field=models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='staff',
            name='CB_image',
            field=models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='vendorrequest',
            name='CA_image',
            field=models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='vendorrequest',
            name='CB_image',
            field=models.ImageField(blank=True, default='/default_image.png', null=True, upload_to='images'),
        ),
    ]
