# Generated by Django 3.0.5 on 2024-01-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_auto_20240121_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
