# Generated by Django 3.0.5 on 2024-01-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20240125_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
