# Generated by Django 3.0.5 on 2024-01-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_auto_20240125_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorrequest',
            name='pan_number',
        ),
    ]
