# Generated by Django 3.0.5 on 2024-01-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_remove_vendorrequest_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
        migrations.AddField(
            model_name='vendorrequest',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
    ]
