# Generated by Django 3.0.5 on 2024-01-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20240127_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='experience',
            field=models.IntegerField(default='1'),
        ),
    ]
