# Generated by Django 3.0.5 on 2024-01-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
