# Generated by Django 3.0.5 on 2024-01-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_auto_20240129_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
