# Generated by Django 3.0.5 on 2024-01-29 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0038_auto_20240129_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber')], default='Electrician', max_length=50)),
                ('day', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(default='')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('isFinished', models.CharField(default='No', max_length=15)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('staff', models.CharField(default='Not assigned', max_length=50)),
                ('payment_status', models.CharField(default='Cash On Delivery', max_length=100)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
