# Generated by Django 3.0.5 on 2024-01-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0039_deletedappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
