# Generated by Django 3.0.5 on 2024-02-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_auto_20240131_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Staff'),
        ),
        migrations.AlterField(
            model_name='deletedappointment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Staff'),
        ),
    ]
