# Generated by Django 3.0.5 on 2024-02-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_auto_20240205_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dispute_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dispute_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
