# Generated by Django 5.0.2 on 2024-02-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_remove_appointment_chat_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tier',
            field=models.CharField(default='bronze', max_length=20),
        ),
    ]
